import fs from 'fs';
import path from 'path';

export const OPENCLAW_WORKER_SHIM_MARKER =
  'Generated by WULU. Bridges gateway-bundle.mjs worker resolution to dist/agents.';

export const OPENCLAW_WORKER_SHIM_TARGETS = [
  {
    shimFile: 'model-provider-auth.worker.mjs',
    targetFile: path.join('dist', 'agents', 'model-provider-auth.worker.js'),
  },
  {
    shimFile: 'code-mode.worker.mjs',
    targetFile: path.join('dist', 'agents', 'code-mode.worker.js'),
  },
  {
    shimFile: 'compaction-planning.worker.mjs',
    targetFile: path.join('dist', 'agents', 'compaction-planning.worker.js'),
  },
] as const;

export interface OpenClawWorkerShimResult {
  created: string[];
  updated: string[];
  unchanged: string[];
  missingTargets: string[];
  protectedExisting: string[];
  skippedBecauseBundleMissing: boolean;
}

function toImportPath(filePath: string): string {
  return filePath.split(path.sep).join('/');
}

export function buildOpenClawWorkerShimContent(targetFile: string): string {
  return [
    `// ${OPENCLAW_WORKER_SHIM_MARKER}`,
    `import './${toImportPath(targetFile)}';`,
    '',
  ].join('\n');
}

export function isGeneratedOpenClawWorkerShim(content: string): boolean {
  return content.includes(OPENCLAW_WORKER_SHIM_MARKER);
}

export function ensureOpenClawWorkerShims(runtimeRoot: string): OpenClawWorkerShimResult {
  const result: OpenClawWorkerShimResult = {
    created: [],
    updated: [],
    unchanged: [],
    missingTargets: [],
    protectedExisting: [],
    skippedBecauseBundleMissing: false,
  };

  if (!fs.existsSync(path.join(runtimeRoot, 'gateway-bundle.mjs'))) {
    result.skippedBecauseBundleMissing = true;
    return result;
  }

  for (const target of OPENCLAW_WORKER_SHIM_TARGETS) {
    const targetPath = path.join(runtimeRoot, target.targetFile);
    const shimPath = path.join(runtimeRoot, target.shimFile);
    if (!fs.existsSync(targetPath)) {
      result.missingTargets.push(target.shimFile);
      continue;
    }

    const expectedContent = buildOpenClawWorkerShimContent(target.targetFile);
    if (fs.existsSync(shimPath)) {
      const existing = fs.readFileSync(shimPath, 'utf8');
      if (existing === expectedContent) {
        result.unchanged.push(target.shimFile);
        continue;
      }
      if (!isGeneratedOpenClawWorkerShim(existing)) {
        result.protectedExisting.push(target.shimFile);
        continue;
      }
      fs.writeFileSync(shimPath, expectedContent, 'utf8');
      result.updated.push(target.shimFile);
      continue;
    }

    fs.writeFileSync(shimPath, expectedContent, 'utf8');
    result.created.push(target.shimFile);
  }

  return result;
}
